### ISSUE TITLE
(build) loadingGif

### ISSUE THREAD

**Issue by mathe42** [EC-Nordbund/ec-verwaltungs-app#167]
Ein loadingGif für den Installer

**Comment by tobikrs** [comment]
Gibts größen vorgaben? Bzw. wie groß wird er dann sein?

**Comment by mathe42** [comment]
Brauchen wir wahrschienlich nicht mehr für den Installer aber könnte evtl. anderweitig genutzt werden...

**Comment by tobikrs** [comment]
Also erstmal nicht so wichtig...

Bitte, **_reopen_** wenn use-case vorhanden ist.
