### ISSUE TITLE
(design) Personen Details

### ISSUE THREAD

**Issue by mathe42** [EC-Nordbund/ec-verwaltungs-app#223]
Class "isOld" anpassen.

**Comment by tobikrs** [comment]
efad7bb69d736b81ee1915fe6bb2710528e1001a grey icon color it deprecated (isOld)

**Comment by tobikrs** [comment]
ich habe gesehen, dass es eine `markedClass` und eine `marked` option gibt.

Wird die noch für andere Zwecke als `isOld` verwendet?
Wenn nicht, kann diese entfernt werden.
