### ISSUE TITLE
[Bug] Manche Personen-Details lassen sich nicht öffnen

### ISSUE THREAD

**Issue by tobikrs** [EC-Nordbund/ec-verwaltungs-app#267]
Mache Personen lassen sich von der Personen-Liste nicht öffnen.

In der Konsole ist folgender Error:
```
Uncaught (in promise) Error: GraphQL error: val.getDate is not a function
GraphQL error: val.getDate is not a function
```

Personen bei den es bei mir **nicht** geklappt hat (IDs):   `19`,  `20`, `3`

Personen bei den funktioniert:   `0`, `11`, `18886`

**Comment by tobikrs** [comment]
Programm-Version: [1.0.2](https://github.com/EC-Nordbund/ec-verwaltungs-app/releases/tag/v1.0.2)

**Comment by mathe42** [comment]
Kein Bug nur fehlerhafte Daten bei allen die ein FZ haben
