### ISSUE TITLE
Please provide the AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [EC-Nordbund/ec-verwaltungs-app#290]
https://github.com/EC-Nordbund/ec-verwaltungs-app/blob/f18d31cbcc16ea5f4268c861b5692d5a860988c3/packages/app/vue.config.js#L31

Please provide the AppImage on https://github.com/EC-Nordbund/ec-verwaltungs-app/releases, thank you.

**Comment by mathe42** [comment]
This Repro is currently in Development.

It is Open Source but you can not run it without run your own API and own MySQL-Server. {Password Protection}

Also everything is in German...

You can try https://github.com/EC-Nordbund/ec-verwaltungs-app/releases/tag/v1.2.1 ...

**Comment by probonopd** [comment]
Deutsch wäre kein Problem aber ich sehe dort leider kein [AppImage](https://appimage.org/)... https://github.com/EC-Nordbund/ec-verwaltungs-app/releases/tag/v1.2.1

**Comment by mathe42** [comment]
Du kannst ec-verwaltungs-app_1.2.1_amd64.deb nutzen. {sollte auch gehen...}
